[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "link-arg=-zstack-size=65536", 
    "-C", "target-feature=+bulk-memory",
    "-C", "target-feature=-reference-types",
    "-C", "target-feature=-simd128", 
    "-C", "target-feature=-sign-ext",
    "-C", "target-feature=-multivalue",
    "-C", "target-feature=-mutable-globals",
]
